site_name: ISO TC 204 Information
site_description: Information about ISO TC 204 standardization efforts
repo_url: https://github.com/ISO-TC204/ISO-TC204.github.io
nav:
  - Home: index.md
  - About:
    - About TC 204: about.md
    - About ISO Documents: about-docs.md
    - Intro to ITS: intro.md
    - Business Plan: assets/pdf/business-plan-2008-04-06.pdf
    - Contact us: contact.md
    - Vocabulary: vocab.md
    - Acknowledgements: acknowledgements.md
    - Contributions: contributor.md
    - FAQs: faq.md
  - Work: 
    - Overview: work.md
    - Foundational concepts: foundational.md
    - Architecture (WG 1): wg1/index.md
    - Big data and AI (WG 20): wg20/index.md
    - City data model - Transport (JWG 1): jwg1/index.md
    - Communications (WG 16): wg16/index.md
    - Cooperative systems (WG 18): wg18/index.md
    - Coordination (AG 4): ag4/index.md
    - Cybersecurity (AHG 2): ahg2/index.md
    - Driving automation and active safety systems (WG 14): wg14/index.md
    - Fee and toll collection (WG 5): wg5/index.md
    - Fleet management (WG 7): wg7/index.md
    - Geographic data (WG 3): wg3/index.md
    - Identifiers (AG 2): ag2/index.md
    - Mobility integration (WG 19): wg19/index.md
    - Nomadic devices in ITS (WG 17): wg17/index.md
    - Operational improvement (AG 3): ag3/index.md
    - Public transport/emergency (WG 8): wg8/index.md
    - Publication and marketing (AG 5): ag5/index.md
    - Registry for ITS Identifiers (AG 2): ag2/index.md
    - Transport mgmt and control (WG 9): wg9/index.md
    - Traveller information (WG 10): wg10/index.md
  - Registries: 
    - Overview: registries.md
    - Registry for ITS Identifiers (RITSI): https://iso-tc204.github.io/iso5345/
    - Registry for ITS Ontologies (RITSO): https://k-vaughn.github.io/ontologies/latest/
  - Standards: 
    - Overview: standards.md
    - METR: https://iso-tc204.github.io/iso24315/
  - Cybersecurity: 
    - Introduction: cybersecurity/index.md
    - Beginners Guide: cybersecurity/beginners-guide.md 
    - ITS Cybersecurity Patterns: 
      - Overview: cybersecurity/its-security-patterns.md
      - Secure ITS Management Patterns: cybersecurity/patterns-management.md
      - Application Security Patterns: cybersecurity/patterns-application.md
      - Edge Device Security Patterns: cybersecurity/patterns-edge.md
      - Network and Transport Security Patterns: cybersecurity/patterns-network.md
      - Deployment and Integration Security Patterns: cybersecurity/patterns-deployment.md
      - Developer Patterns: cybersecurity/patterns-developer.md
    - ITS Security Regulations and Standards: 
      - Overview: cybersecurity/its-security-standards.md
      - Certificate Policy (CP): cybersecurity/policies-cp.md
      - SCMS Policy: cybersecurity/policies-scms.md
      - CCMS Policy: cybersecurity/policies-ccms.md
      - Device Security Policy Configurations: cybersecurity/policies-device.md
    - ITS Threat analysis: cybersecurity/threat-analysis.md
    - Interoperability strategies: cybersecurity/its-interoperability-strategies.md
    - Stakeholder guidance: 
      - Overview: cybersecurity/its-stakeholder-guidance.md
      - Standards developers: cybersecurity/stakeholder-standards-developer.md
      - Cybersecurity Oversight and Policy Authorities: cybersecurity/stakeholder-policy-maker.md
      - Infrastructure Owner Operators (IOOs): cybersecurity/stakeholder-ioo.md
      - ITS Application Developers: cybersecurity/stakeholder-appdev.md
      - Certificate Management Authorities: cybersecurity/stakeholder-certmgmt.md
      - Original Equipment Manufacturers (OEMs): cybersecurity/stakeholder-oem.md
    - Misuse Cases: cybersecurity/its-misuse-cases.md
    - Secure ITS Management Patterns: cybersecurity/patterns-management.md
    - Glossary: cybersecurity/cybersecurity-glossary.md
  - Resources: resources.md
site_url: https://iso-tc204.github.io
copyright: CC BY 4.0
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.tooltips
    - header.auto_hide
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - git-revision-date-localized:
      type: date
  - include-markdown
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - resources/glossary.md
  - pymdownx.superfences
  - toc:
      permalink: true
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra:
  search:
    highlight: true



    
    