site_name: ISO TC 204 Information
site_description: Information about ISO TC 204 standardization efforts
repo_url: https://github.com/ISO-TC204/ISO-TC204.github.io
nav:
  - Home: 
    - Welcome: index.md
    - Overview: overview.md
    - About us: about.md
    - Intro to ITS: intro.md
    - Cybersecurity: 
      - Overview: cybersecurity/index.md
      - Introduction: cybersecurity/beginners-guide.md
      - Security architectures: cybersecurity/its-security-architectures.md
      - Security standards: cybersecurity/security-standards.md
      - ITS Threat analysis: cybersecurity/ITS-Threat-Analysis.md
      - Interoperability strategies: cybersecurity/interoperability-strategies.md
      - Cybersecurity controls: cybersecurity/its-cybersecurity-controls.md
      - Stakeholder guidance: 
        - Overview: cybersecurity/stakeholder-guidance.md
        - Standards developers: cybersecurity/standards-developers.md
        - Decision makers: cybersecurity/policy-makers.md
        - Implementers: cybersecurity/implementers.md
      - Cybersecurity policies: cybersecurity/security-policies.md
      - Specialized use cases: cybersecurity/specialized-use-cases.md
      - Glossary: cybersecurity/Glossary.md
    - TC 204 planning: planning.md
    - Contact us: contact.md
    - Resources: resources.md
    - Vocabulary: vocab.md
    - Acknowledgements: acknowledgements.md
  - Our work: 
    - Overview: work.md
    - Foundational concepts: foundational.md
    - Architecture (WG 1): wg1/index.md
    - Big data and AI (WG 20): wg20/index.md
    - City data model - Transport (JWG 1): jwg1/index.md
    - Communications (WG 16): wg16/index.md
    - Cooperative systems (WG 18): wg18/index.md
    - Coordination (AG 4): ag4/index.md
    - Cybersecurity (AHG 2): ahg2/index.md
    - Driving automation and safety (WG 14): wg14/index.md
    - Fee and toll collection (WG 5): wg5/index.md
    - Fleet management (WG 7): wg7/index.md
    - Geographic data (WG 3): wg3/index.md
    - Identifiers (AG 2): ag2/index.md
    - Mobility integration (WG 19): wg19/index.md
    - Nomadic devices in ITS (WG 17): wg17/index.md
    - Operational improvement (AG 3): ag3/index.md
    - Public transport/emergency (WG 8): wg8/index.md
    - Publication and marketing (AG 5): ag5/index.md
    - Registry for ITS Identifiers (AG 2): ag2/index.md
    - Transport mgmt and control (WG 9): wg9/index.md
    - Traveller information (WG 10): wg10/index.md
  - Contributions:
    - Overview: contributor/index.md
    - Commenter guidelines: contributor/commenter.md
    - Editor guidelines: contributor/editor.md
    - Convenor guidelines: contributor/convenor.md
  - News: news.md
  - FAQs: faq.md
site_url: https://iso-tc204.github.io
copyright: CC BY 4.0
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.tooltips
    - header.auto_hide
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - git-revision-date-localized:
      type: date
  - include-markdown
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - resources/glossary.md
  - pymdownx.superfences
  - toc:
      permalink: true
extra_css:
  - assets/stylesheets/extra.css
extra:
  search:
    highlight: true



    
    